name: amd64 mac-15 ninja cl-21 fl-21

on:
  push:
    branches: main
jobs:
  build:
    runs-on: macos-15-intel
    steps:
      - name: install
        run: |
          brew update
          brew install flang
      - name: checkout
        uses: actions/checkout@v5.0.0
      - name: test
        run: |
          ls /usr/local/bin/flang*
