name: conda iowarp-core

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: apt
        run: |
          sudo apt update
          sudo apt -y install libstdc++6
      - name: miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge, iowarp
#          auto-update-conda: true
          python-version: 3.11

      - name: checkout
        uses: actions/checkout@v5
        with:
          repository: iowarp/core
          submodules: recursive

      - name: iowarp
        run: |
          export CMAKE_PREFIX_PATH=$CONDA_PREFIX
          conda install -y conda-build
          conda install -y conda-verify
          conda install -y anaconda-client
          export PATH=/usr/share/miniconda/bin:$PATH
          which anaconda
          git tag v0.6.5
          conda-build .
#          conda install iowarp-core
#          find /usr/share/miniconda
#          /usr/share/miniconda/bin/chimaera_start_runtime &
#          /usr/share/miniconda/bin/wrp_cae
#          echo $CONDA_PREFIX
#          which chimaera_start_runtime
#          conda install -c conda-forge libgcc-ng
#          conda install -y libgcc-ng=11.2.0
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: iowarp-core-0.6.5-py313h3fd9d12_0.conda
          path: /usr/share/miniconda/conda-bld/linux-64/iowarp-core-0.6.5-py313h3fd9d12_0.conda
      - name: release
#        if: startsWith(github.ref, 'refs/tags/v')
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          export PATH=/usr/share/miniconda/bin:$PATH
          if [ -z "$ANACONDA_TOKEN" ]; then
            echo "ANACONDA_TOKEN is not set. Skipping upload."
            exit 0
          fi
          anaconda login
          anaconda -v upload /usr/share/miniconda/conda-bld/linux-64/iowarp-core-0.6.5-py313h3fd9d12_0.conda
