name: lin-24 conda iowarp-core

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-24.04
    steps:
      - name: apt
        run: |
          sudo apt update
          sudo apt -y install libstdc++6
      - name: miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.13
          channels: conda-forge
      - name: iowarp
        run: |
          conda install -c conda-forge libgcc-ng
          conda install -y libgcc-ng=11.2.0
          conda install -c iowarp -c conda-forge iowarp-core
          which chimaera_start_runtime
