name: Linux Static-Only Build CI

on:
  workflow_dispatch:
  push:
    branches: main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: "Ubuntu Static-Only Build"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
         os: [ubuntu-24.04]
#        os: [ubuntu-24.04, ubuntu-22.04]
#        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-24.04-arm]
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build graphviz
          sudo apt install gfortran
      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: HDFGroup/hdf5
      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -G Ninja \
            -DBUILD_SHARED_LIBS:BOOL=OFF \
            -DBUILD_STATIC_LIBS:BOOL=ON \
            -DHDF5_ONLY_SHARED_LIBS:BOOL=OFF \
            -DHDF5_BUILD_CPP_LIB:BOOL=ON \
            -DHDF5_BUILD_FORTRAN:BOOL=ON \
            -DSITE:STRING="${{ matrix.os }}" -DBUILDNAME:STRING="st/-stl/-sxc/cpp" -DCTEST_DROP_SITE_INIT:STRING="my.cdash.org" -DCTEST_DROP_LOCATION_INIT:STRING="/submit.php?project=HDF5" \
            ..
          ctest -D Experimental
