name: macOS DMG Installation and Run

on:
  push:
    branches: [main-]

jobs:
  install-and-run:
    runs-on: macos-26
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download DMG file
        run: curl -L https://support.hdfgroup.org/releases/hdf5/v1_14/v1_14_5/downloads/snapshot-1.14.5-macos14_clang.dmg -o app.dmg

      - name: Attach DMG file
        run: |
          hdiutil convert -quiet app.dmg -format UDTO -o bar
          hdiutil attach -quiet -nobrowse -noverify -noautoopen -mountpoint /Volumes/app bar.cdr

      - name: Test application
        run: /Volumes/app/HDF_Group/HDF5/1.14.5.2/bin/h5ls -h

      - name: Detach DMG file
        run: hdiutil detach /Volumes/app

