name: mac-26 spack h5py

on:
  push:
    branches: [ main- ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-26

    steps:
    - name: Checkout Spack
      uses: actions/checkout@v6
      with:
        repository: spack/spack
        path: ./spack
    - name: Run a multi-line script
      run: |
        . ./spack/share/spack/setup-env.sh
        ./spack/bin/spack spec py-h5py@master+mpi
         sed -i '' 's/hdf5@1.10.6:1.14/hdf5@1.10.6:/g' \
        ~/.spack/package_repos/*/repos/spack_repo/builtin/packages/py_h5py/package.py
        ./spack/bin/spack spec py-h5py@master+mpi ^hdf5@develop-2.0
        ./spack/bin/spack install py-h5py@master+mpi ^hdf5@develop-2.0
        ./spack/bin/spack install py-pytest
        ./spack/bin/spack install py-pytest-mpi
        spack load py-h5py
        spack load py-pytest
        pip install pytest-mpi
        export H5PY_TEST_CHECK_FILTERS=1
        python -c "import h5py; h5py.run_tests(); print(h5py.version.info);"
