name: musl

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: "muslcc/x86_64:x86_64-linux-musl"    
    steps:
      - name: Use Node.js 20.x on Alpine
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          check-latest: true      
      - name: checkout
        uses: actions/checkout@v6
        with:
          repository: HDFGroup/hdf5

      - name: run script
        run: |
          sudo apt install -y gfortran-14-riscv64-linux-gnu
          mkdir build
          cd build
          cmake -DSITE:STRING=musl \
            -DBUILDNAME:STRING="r" \
            -DCTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
            -DCTEST_DROP_LOCATION_INIT="/submit.php?project=HDF5" \
             ..
          ctest -D Experimental -C Release

