name: musl

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: "muslcc/x86_64"    
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          repository: HDFGroup/hdf5

      - name: run script
        run: |
          sudo apt install -y gfortran-14-riscv64-linux-gnu
          mkdir build
          cd build
          cmake -DSITE:STRING=musl \
            -DBUILDNAME:STRING="r" \
            -DCTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
            -DCTEST_DROP_LOCATION_INIT="/submit.php?project=HDF5" \
             ..
          ctest -D Experimental -C Release

