name: musl

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: "muslcc/x86_64:x86_64-linux-musl"    
    steps:
      - name: test
        run: |
          apk add cmake git build-base
          git clone https://github.com/HDFGroup/hdf5
          cd hdf5
          mkdir build
          cd build
          cmake -DSITE:STRING=musl \
            -DBUILDNAME:STRING="r" \
            -DCTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
            -DCTEST_DROP_LOCATION_INIT="/submit.php?project=HDF5" \
             ..
          ctest -D Experimental -C Release

