name:  obsd-7.8 ompi cpp

on:
  push:
    branches: main

jobs:
  test:
    name: ${{ matrix.os.name }} ${{ matrix.os.architecture }} ${{ matrix.os.version }} on ${{ matrix.os.host }}
    runs-on: ${{ matrix.os.host }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: openbsd
            architecture: x86-64
            version: '7.8'
            host: ubuntu-latest
    steps:
      - name: get
        uses: actions/checkout@v6
        with:
          repository: dutkalex/hdf5
          ref: patch-1
          path: .

      - name: ${{ matrix.os.name }}
        uses: cross-platform-actions/action@v0.32.0
        with:
          operating_system: ${{ matrix.os.name }}
          architecture: ${{ matrix.os.architecture }}
          version: '${{ matrix.os.version }}'
          shell: bash
          run: |
            sudo pkg_add cmake
            sudo pkg_add openmpi
            export NPROCS=2
            export PMIX_MCA_gds=hash
            export OMPI_MCA_btl=self,tcp
            mkdir build
            cd build
            cmake \
              -DBUILDNAME="pr6145/ompi/cpp" \
              -DCTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
              -DHDF5_ALLOW_UNSUPPORTED=ON \
              -DHDF5_BUILD_CPP_LIB:BOOL=ON \
              -DHDF5_ENABLE_PARALLEL:BOOL=ON \
              -DMPIEXEC_PREFLAGS="-oversubscribe" \
              -DSITE:STRING="obsd-7.8" \
            ..
            ctest -D Experimental
