name: obsd vm f

on:
  push:
    branches: main-

defaults:
  run:
    shell: bash
jobs:
  build:
    name: obsd vm f
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          repository: brtnfld/hdf5
          ref: H5R
      - name: test
        uses: vmactions/openbsd-vm@v1
        with:
          release: "7.8"
          usesh: true
          run: |
            pkg_add cmake
            pkg_add g95-11.2.0p19            
            mkdir build
            cd build
            cmake -DSITE:STRING="obsd-7.8" \
            -DBUILDNAME:STRING="pr5931/d/cpp/+hl+ts-sz-zl/da+dw+tv" \
            -DCTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
            -DCTEST_DROP_LOCATION_INIT:STRING="/submit.php?project=HDF5" \
            -DCMAKE_BUILD_TYPE=Release \
            -DHDF5_ALLOW_UNSUPPORTED:BOOL=ON \
            -DHDF5_BUILD_CPP_LIB:BOOL=ON \
            -DHDF5_BUILD_HL_LIB:BOOL=ON \
            -DHDF5_ENABLE_THREADSAFE:BOOL=ON \
            -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF \
            -DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=OFF \
            -DHDF5_TEST_API=ON -DHDF5_ENABLE_ALL_WARNINGS=ON -DHDF5_ENABLE_DEBUG_APIS:BOOL=ON -DHDF5_ENABLE_DEV_WARNINGS=ON -DHDF5_TEST_VFD:BOOL=ON \
            ..
            ctest -D Experimental -C Debug
