name: ora-10

on:
  push:
    branches:
      - main-

jobs:
  test:
    runs-on: ubuntu-latest
    container: "oraclelinux:10"
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          repository: HDFGroup/hdf5
      - name: test
        run: |
          dnf install -y cmake clang
          mkdir build
          cd build
          cmake \
            -DSITE:STRING="ora-10" \
            -DBUILDNAME:STRING="r" \
            -DCTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
            ..
          ctest -D Experimental
