name: ora-10 hdf5

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: "oraclelinux:10"
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          repository: HDFGroup/hdf5
      - name: test
        run: |
          dnf install -y cmake gfortran
          mkdir build
          cd build
          cmake \
            -DSITE:STRING="ora-10" \
            -DBUILDNAME:STRING="cpp/f/h/mp" \
            -DCTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
            -DHDF5_BUILD_CPP_LIB:BOOL=ON \
            -DHDF5_BUILD_FORTRAN:BOOL=ON \
            -DHDF5_BUILD_HL_LIB:BOOL=ON \
            -DHDF5_ENABLE_MAP_API:BOOL=ON \
            ..
          ctest -D Experimental
