name: vm gcc f

on:
  push:
    branches: main

defaults:
  run:
    shell: bash
jobs:
  build:
    name: vm gcc f
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          repository: brtnfld/hdf5
          ref: H5R
      - name: test
        uses: vmactions/openbsd-vm@v1
        with:
          release: "7.8"
          usesh: true
          run: |
            pkg_add cmake
            pkg_add g95-11.2.0p19
            export FC=/usr/local/bin/egfortran
            export CC=/usr/local/bin/egcc
            mkdir build
            cd build
            cmake \
            -D BUILDNAME="brtnfld/vm/gcc/f" \
            -D CTEST_DROP_SITE_INIT="my.cdash.org" \
            -D HDF5_BUILD_FORTRAN=ON \
            -D SITE="obsd-7.8" \
            ..
            ctest -T Build
            ctest -VV --output-on-failure -T Test -R FORTRAN_testhdf5_fortran
